"""rename department

Revision ID: 8d86c2e2c9a4
Revises: 26ed136ff33e
Create Date: 2024-12-26 13:00:03.701683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d86c2e2c9a4'
down_revision = '26ed136ff33e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
